<?php

namespace ResumeBundle\Repository;

/**
 * GeneralSkillsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralSkillsRepository extends \Doctrine\ORM\EntityRepository
{
}
