<?php

namespace ResumeBundle\Repository;

/**
 * GeneralSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
