<?php

namespace ResumeBundle\Repository;

/**
 * SpecificSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecificSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
